"""Write public/assets/characters/README.md from the verification report (run verify_glb.py
first) and anims_humanoid.json."""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import cw_paths as P
from characters_cfg import CHARACTERS


def main():
    rep = json.load(open(os.path.join(P.WORK, "verify_report.json")))
    meta = json.load(open(os.path.join(P.OUT, "anims_humanoid.json")))
    L = []
    L.append("# Characters\n")
    L.append("Generated by `tools/assets/characters/` (see the README there for how to rebuild). "
             "Units metres, +Y up, characters face +Z, feet at y = 0, rest pose = MakeHuman A-pose. "
             "All character files share **one skeleton (63 bones)** with identical bone names and rest "
             "pose; `anims_humanoid.glb` carries the same skeleton plus every clip, so a single "
             "`THREE.AnimationMixer` clip set drives every character by bone name.\n")
    L.append("## Files\n")
    L.append("| File | Content | LOD0 tris | LOD1 tris | Height m (node scale) | Size |")
    L.append("|---|---|---:|---:|---:|---:|")
    for cid, c in CHARACTERS.items():
        r = rep.get(cid)
        if not r:
            continue
        if cid == "warden_woman":
            L.append("| **London, East End, Sept 1940** | | | | | |")
        extra = ""
        if cid == "officer":
            extra = " Extra mesh `cap` (soft service cap, %d tris) - **hide it by default** (`cap.visible = false`); " \
                    "show it and hide the helmet primitive if wanted." % r["meshes"].get("cap", 0)
        if "bundle" in r["meshes"]:
            extra = " Extra mesh `bundle` (wrapped baby, %d tris, rigid to the chest) - **hide it by default**; " \
                    "it sits between the hands of `carry_box`." % r["meshes"]["bundle"]
        L.append("| `%s.glb` | %s.%s Meshes `%s` (LOD0) and `%s_LOD1`. | %d | %d | %.2f (%.3g) | %.2f MB |" % (
            cid, c["desc"], extra, cid, cid, r["lod0"], r["lod1"], r["height"], r.get("scale", 1.0), r["bytes"] / 1e6))
    a = rep["anims_humanoid"]
    L.append("| `anims_humanoid.glb` | Skeleton (63 bones + root node, no mesh) and %d clips | - | - | - | %.2f MB |" % (
        len(a["clips"]), a["bytes"] / 1e6))
    L.append("| `anims_humanoid.json` | Clip metadata `{duration, loop, speed, source[, notes]}` | - | - | - | - |")
    f = rep["fp_arms"]
    L.append("| `fp_arms.glb` | First-person forearms + hands, charcoal wool sleeves, temporal device on the LEFT "
             "wrist (emissive material `device_screen`), folded paper prop `fp_paper` (shown only by `fp_hold` via "
             "the `prop.R` bone scale). Own rig: %d bones. Camera space: origin = camera, looking -Z, +Y up. | %d | - | - | %.2f MB |"
             % (f["bones"], f["tris"], f["bytes"] / 1e6))
    L.append("")
    L.append("Each character GLB holds one skinned mesh per LOD with these primitives/materials (draw calls): "
             "`skin`, `eyes`, `hair`, `cloth` (wool garments, double-sided), `gear` (webbing/leather/boots/brass) and "
             "`helmet` (where worn). LOD1 reuses the LOD0 materials/textures. Height = top of the rest-pose mesh "
             "(incl. helmet/hat).\n")
    L.append("**Node scale.** Women, children and the elderly are smaller than the canonical skeleton: their bodies are "
             "fitted to the canonical skeleton x scale and the GLB's `Armature` node carries that uniform scale "
             "(e.g. 0.93 for the women, 0.78 / 0.69 for the girl / boy). Bones, rest pose and every clip are identical "
             "for all characters, so the shared clips play unchanged (the hips translation is scaled with the node). "
             "Do not reset the `Armature` node's scale; multiply your own placement scale onto it. Locomotion speeds in "
             "the json are for scale 1: use `timeScale = actualSpeed / (speed * scale)`. The children keep adult limb "
             "proportions (same skeleton) with child heads/faces/bodies.\n")
    L.append("## Skeleton (63 bones)\n")
    L.append("`root` (origin, never animated) > `hips` > `spine05..spine01` > `neck01`, `neck02`, `head`, `jaw`; "
             "per side `pelvis`, `upperleg01/02`, `lowerleg01/02`, `foot`, `toes`; `clavicle`, `shoulder01`, "
             "`upperarm01/02`, `lowerarm01/02` (twist bones), `wrist`, fingers `finger1-1..3` (thumb), `finger2` (index), "
             "`finger3` (middle), `finger4` (ring + little finger merged). Dropped MakeHuman bones (face, toes, "
             "breast, metacarpals, little finger, neck03, eyes) were merged into their kept ancestor (little finger "
             "into the ring chain). Only `hips` has a translation track that varies.\n")
    L.append("## Clips (`anims_humanoid.glb`)\n")
    L.append("| Clip | Duration s | Loop | Ground speed m/s | Source / notes |")
    L.append("|---|---:|:---:|---:|---|")
    for k, m in meta.items():
        L.append("| `%s` | %.2f | %s | %s | %s%s |" % (k, m["duration"], "yes" if m["loop"] else "no",
                                                    ("%.3f" % m["speed"]) if m["speed"] else "0",
                                                    m.get("source", ""), (" - " + m["notes"]) if "notes" in m else ""))
    L.append("\nLocomotion clips are in place (linear root trend removed, stance feet IK-locked); play them with "
             "`timeScale = actualSpeed / (speed * nodeScale)` to avoid foot sliding.\n")
    L.append("## First-person clips (`fp_arms.glb`)\n")
    L.append("| Clip | Duration s | Loop |")
    L.append("|---|---:|:---:|")
    for n, d in f["clips"]:
        L.append("| `%s` | %.2f | %s |" % (n, d, "no" if n == "fp_reach" else "yes"))
    L.append("\n`fp_idle` keeps the hands just below a 70 deg vertical FOV; `fp_reach` (one-shot) reaches forward and "
             "presses; `fp_hold` holds the paper in view; `fp_scan` raises the left forearm with the device facing the "
             "camera; `fp_grip_two` grips two handles (stretcher/crowbar) with a walking bob; `fp_climb` alternates hands "
             "up a ladder (rungs 0.3 m apart, 1.6 s cycle = 0.375 m/s climb).\n")
    L.append("## Textures\n")
    L.append("Embedded JPEG (quality 85-90), PBR metal/rough with separate occlusion (ORM: R = AO, G = roughness, "
             "B = metalness), tangent-space normal maps (OpenGL +Y). Per character: skin 1024² (albedo, normal, ORM), "
             "cloth 1024² (albedo, normal, ORM), gear 1024² albedo/normal + 512² ORM, helmet 512², hair 512² "
             "(ORM 256²), eyes 256² albedo (+128² ORM). fp_arms: skin and sleeve 1024² (ORM 512²), device 256², "
             "screen 256² emissive, paper 128². All textures are procedural own work.\n")
    out = os.path.join(P.OUT, "README.md")
    open(out, "w").write("\n".join(L) + "\n")
    print("wrote", out)


if __name__ == "__main__":
    main()
